SRCS:=\
	class_ut_00.cpp class_ut_01.cpp class_ut_02.cpp class_ut_03.cpp class_ut_04.cpp class_ut_05.cpp \
	class_ut_06.cpp class_ut_07.cpp class_ut_08.cpp class_ut_09.cpp const_ut.cpp this_ut.cpp c_syle_ut.cpp \
	new_delete_ut.cpp

CPP_VER = c++20
OBJDIR:=
SHARED:=../../deep/
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
