SRCS:=\
	class_ut_0.cpp class_ut_1.cpp class_ut_2.cpp class_ut_3.cpp class_ut_4.cpp class_ut_5.cpp \
	class_ut_6.cpp class_ut_7.cpp class_ut_8.cpp \
   	c_syle_ut.cpp \

CPP_VER = c++20
OBJDIR:=
SHARED:=../../deep/
include $(SHARED)make/env.mk
include $(SHARED)make/example.mk
include $(SHARED)make/gtest.mk
